// Autogenerated from Pigeon (v22.6.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Any?

  init(code: String, message: String?, details: Any?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
      }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

/// Generated class from Pigeon that represents data sent in messages.
struct ScreenRecordingState {
  var isRecording: Bool



  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ScreenRecordingState? {
    let isRecording = pigeonVar_list[0] as! Bool

    return ScreenRecordingState(
      isRecording: isRecording
    )
  }
  func toList() -> [Any?] {
    return [
      isRecording
    ]
  }
}

private class ScreenRecorderCallbackApiPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return ScreenRecordingState.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class ScreenRecorderCallbackApiPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? ScreenRecordingState {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class ScreenRecorderCallbackApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return ScreenRecorderCallbackApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return ScreenRecorderCallbackApiPigeonCodecWriter(data: data)
  }
}

class ScreenRecorderCallbackApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = ScreenRecorderCallbackApiPigeonCodec(readerWriter: ScreenRecorderCallbackApiPigeonCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol ScreenRecorderControlApi {
  func startListening() throws
  func stopListening() throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class ScreenRecorderControlApiSetup {
  static var codec: FlutterStandardMessageCodec { ScreenRecorderCallbackApiPigeonCodec.shared }
  /// Sets up an instance of `ScreenRecorderControlApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: ScreenRecorderControlApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let startListeningChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.screen_recorder_callback.ScreenRecorderControlApi.startListening\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startListeningChannel.setMessageHandler { _, reply in
        do {
          try api.startListening()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      startListeningChannel.setMessageHandler(nil)
    }
    let stopListeningChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.screen_recorder_callback.ScreenRecorderControlApi.stopListening\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      stopListeningChannel.setMessageHandler { _, reply in
        do {
          try api.stopListening()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      stopListeningChannel.setMessageHandler(nil)
    }
  }
}
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol ScreenRecordingCallbackApiProtocol {
  func onScreenRecordingChange(state stateArg: ScreenRecordingState, completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class ScreenRecordingCallbackApi: ScreenRecordingCallbackApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: ScreenRecorderCallbackApiPigeonCodec {
    return ScreenRecorderCallbackApiPigeonCodec.shared
  }
  func onScreenRecordingChange(state stateArg: ScreenRecordingState, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.screen_recorder_callback.ScreenRecordingCallbackApi.onScreenRecordingChange\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([stateArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
}
