name: screen_recorder_callback
description: "Screen Recorder CallBack"
version: 0.0.1
homepage:

environment:
  sdk: ^3.5.4
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  pigeon:


flutter:

  plugin:
    platforms:
      android:
        package: com.tajaouart.screen_recorder_callback
        pluginClass: ScreenRecorderCallbackPlugin

      ios:
        pluginClass: ScreenRecorderCallbackPlugin
        fileName: screen_recorder_callback.swift
