name: screen_recorder_callback
description: "Screen Recorder Callback plugin for detecting screen recording on Android and iOS."
version: 0.0.1
homepage: https://github.com/tajaouart/screen_recorder_callback

environment:
  sdk: ^3.5.4
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  pigeon: ^1.0.5

flutter:
  plugin:
    platforms:
      android:
        package: com.tajaouart.screen_recorder_callback
        pluginClass: ScreenRecorderCallbackPlugin
        # Minimum SDK 35 required for screen recording detection support
        minSdkVersion: 35

      ios:
        pluginClass: ScreenRecorderCallbackPlugin
        fileName: screen_recorder_callback.swift
        # Minimum iOS version required for screen recording detection
        platform: ios
        minOsVersion: '11.0'